title : Internet of Things and APIs

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: internet-of-things
destination: internet-of-things

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10
paginate_path: "/blog/page:num"

production_url : http://internet-of-things.apievangelist.com

BASE_PATH : http://internet-of-things.apievangelist.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
